### ISSUE TITLE
existy() and truthy()

### ISSUE THREAD

**Issue by cdcme** [funjs/book-source#1]
Awesome book. [I love it.](https://plus.google.com/112711404479053398081/posts/NcGGMt473gk)

About your helper predicates, existy() and truthy(), couldn't you just do:

``` javascript
function existy(x) { return x != null; }
function truthy(x) { return !!x; }
```

Granted, it doesn't really illustrate the idea of composing functions from functions but is more succinct, I think.

**Comment by fogus** [comment]
Hi and thank you for the kind words.  The goal of `truthy` is to simplify the truthiness in JavaScript to a model like Ruby (as one example): `null` and `false` are falsey and everything else is truthy.  If I use `!!x` then I'm right back into `0` and `''` being falsey -- the thing I was hoping to avoid. :-)

**Comment by cdcme** [comment]
Oh yeah, of course! Thanks!
