### ISSUE TITLE
truthy needed before truthy used?  true!

### ISSUE THREAD

**Issue by ojingo** [funjs/book-source#5]
just a comment about the ordering of the book... truthy is needed before its shown or discussed in the book. :)  might consider ordering that sooner or at least noting where truthy is coming from otherwise comparator function doesn't work before you know the truthy!

**Comment by fogus** [comment]
The book, like JS, isn't restricted to declaration/use ordering... just kidding... it should totally be fix in the next edition. :-) Thanks.

**Comment by ojingo** [comment]
haha... yea really... damn human brains not hoisting the functions? whats up with that?  

thanks for writing this book... really enjoying it...and now Im looking at your Joy of Clojure book as well and thinking... how many books can I really read at once? haha.  cheers.
