### ISSUE TITLE
Error on page 32

### ISSUE THREAD

**Issue by DannyMoerkerke** [funjs/book-source#6]
There is an error on page 32. It is stated that the following function returns the global Window object, but it returns the object b:

var bFunc = function () { return this; }
var b = { name: "b", fun: bFunc };

b.fun()

console.log(b.fun()); gives:

Object {name: "b", fun: function}

**Comment by joyrexus** [comment]
You might want to consider [submitting](http://www.oreilly.com/cs/catalog/create/errata/?b=34617) this to the book's official [errata list](http://www.oreilly.com/catalog/errata.csp?isbn=0636920028857).

**Comment by eschwartz** [comment]
darn, someone already beat me to it :p 

I see this listed on the Confirmed Errata page you linked to, so you can close this issue.
