### ISSUE TITLE
Fork with coffeescript variants

### ISSUE THREAD

**Issue by joyrexus** [funjs/book-source#7]
FWIW, [my fork](https://github.com/joyrexus/func-js-book) contains CoffeeScript variants of the first three chapters.  I'd welcome contributions from the later chapters if anyone else is working through through the text in this manner (i.e., converting to idiomatic CS).

**Comment by fogus** [comment]
This is fun!  I would love to contribute also, but I sadly can't find the cycles.  I would however be interested in hosting this when it's complete in the funjs account if you're interested.

**Comment by joyrexus** [comment]
@fogus cool, I'll let you know when we're done working through it.  Thanks for [the tweet](https://twitter.com/fogus/status/446264494927671296).

**Comment by joyrexus** [comment]
Update: we're now through [Chapter 4](https://github.com/joyrexus/func-js-book/blob/master/coffee/4.coffee.md).

**Comment by DinisCruz** [comment]
Hi @joyrexus can you add issues to https://github.com/joyrexus/func-js-book that would make it easier to contribute to your changes :)

**Comment by joyrexus** [comment]
@DinisCruz Sure, [done](https://github.com/joyrexus/func-js-book/issues).

**Comment by DinisCruz** [comment]
Btw I've started to add a couple of these methods to fluentnode (see https://github.com/o2platform/fluentnode/issues/29) including unit tests to confirm its behaviour:

``` coffee
require('../src/globals')

describe 'global',->

  it 'existy',->
    existy(null      ).assert_False()
    existy(undefined ).assert_False()
    existy({}.notHere).assert_False()
    existy((()->)()  ).assert_False() # same as existy((function(){})())
    existy(@         ).assert_True()
    existy(0         ).assert_True()
    existy(true      ).assert_True()
    existy(false     ).assert_True()

  it 'truthly',->
    truthly(null     ).assert_False()
    truthly(false    ).assert_False()
    truthly(undefined).assert_False()
    truthly(0        ).assert_True()
    truthly(1        ).assert_True()
    truthly(''       ).assert_True()
    truthly(' '      ).assert_True()
    truthly(true     ).assert_True()
```
